"""added client data to widget data corrected error 3

Revision ID: 7fe712224299
Revises: c749ddfb5618
Create Date: 2023-04-10 19:23:20.890089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe712224299'
down_revision = 'c749ddfb5618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.drop_constraint('widget_data_client_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('widget_data_client_id_key', ['client_id'])

    # ### end Alembic commands ###
